version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - PORT=8080
      - DB_PATH=/data/typinghero.db
      - FRONTEND_ORIGINS=http://localhost:5173
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    volumes:
      - typinghero-data:/data
    networks:
      - typinghero
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/readyz"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        VITE_API_URL: /api
        VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - typinghero

volumes:
  typinghero-data:

networks:
  typinghero:
    driver: bridge
